name: Payment Service Pipeline
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  #pull_request:
   # paths:
    #  - 'apps/payment-service/**' # Path filtering: Triggers ONLY on relevant changes
  workflow_dispatch:  # ← Add this
permissions:
  contents: write
jobs:
  pre-flight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      #- run: npm ci
      #- run: npm run lint && npm run test:unit

  playwright-shards:
    needs: pre-flight
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Launch Test Shard Container
        uses: docker://mcr.microsoft.com/playwright:v1.60.0-noble
        with:
          #args: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
          args: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob

      - name: Save Shard Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report/

  compile-master-report:
    needs: playwright-shards
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Download All Blob Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blobs/
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge Shard Reports
        run: npx playwright merge-reports ./all-blobs --reporter=html
      - name: Upload Master Report           # ← ADD THIS
        uses: actions/upload-artifact@v4     # ← ADD THIS
        if: always()                         # ← ADD THIS
        with:                                # ← ADD THIS
          name: master-report                # ← ADD THIS
          path: playwright-report/           # ← ADD THIS
  
  deploy-report:
    needs: compile-master-report
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: master-report
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
